-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;

CREATE SCHEMA userdata;

CREATE SCHEMA rbac;

CREATE SCHEMA scripts;

CREATE TABLE IF NOT EXISTS userdata.organizations
(
    id bigserial NOT NULL,
    name character varying(128) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS userdata.teams
(
    id bigserial NOT NULL,
    name character varying(128) NOT NULL,
    organization bigint NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS userdata.teams_users
(
    team_id bigint NOT NULL,
    user_id bigint NOT NULL
);

CREATE TABLE IF NOT EXISTS userdata.users
(
    id bigserial NOT NULL,
    name character varying(128) NOT NULL,
    email character varying(320) NOT NULL UNIQUE,
    provider character varying(16) NOT NULL,
    provider_details jsonb NOT NULL,
    password character varying(512),
    verified boolean NOT NULL DEFAULT false,
    organization bigint,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS rbac.resource
(
    id bigserial NOT NULL,
    resource bigint NOT NULL,
    resource_type character varying(16) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS rbac.actions
(
    id bigserial NOT NULL,
    action character varying(16) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS rbac.resource_actions
(
    id bigserial NOT NULL,
    resource_id bigint NOT NULL,
    actions_id bigint NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS rbac.roles
(
    id bigserial NOT NULL,
    name character varying(128) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS rbac.resource_actions_roles
(
    resource_actions_id bigint NOT NULL,
    roles_id bigint NOT NULL
);

CREATE TABLE IF NOT EXISTS rbac.user_organization_roles
(
    user_id bigint NOT NULL,
    roles_id bigint NOT NULL
);

CREATE TABLE IF NOT EXISTS rbac.user_team_roles
(
    team_id bigint NOT NULL,
    roles_id bigint NOT NULL,
    user_id bigint NOT NULL
);

CREATE TABLE IF NOT EXISTS userdata.wallet
(
    id bigserial NOT NULL,
    linked_type character varying(8) NOT NULL,
    linked_id bigint NOT NULL,
    value bigint NOT NULL DEFAULT 0,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS scripts.script
(
    id bigserial NOT NULL,
    name character varying(128) NOT NULL,
    created_by bigint NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    throttle bigint NOT NULL,
    max_runs bigint NOT NULL,
    pause_at jsonb NOT NULL,
    scale jsonb NOT NULL,
    logs jsonb NOT NULL,
    executor_type character varying(8) NOT NULL,
    max_runtime bigint NOT NULL,
    step_max_runtime bigint NOT NULL,
    secrets jsonb NOT NULL,
    linked_to character varying(8) NOT NULL,
    linked_id bigint NOT NULL,
    updated_by bigint NOT NULL,
    PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS userdata.teams
    ADD FOREIGN KEY (organization)
    REFERENCES userdata.organizations (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS userdata.teams_users
    ADD FOREIGN KEY (team_id)
    REFERENCES userdata.teams (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS userdata.users
    ADD FOREIGN KEY (organization)
    REFERENCES userdata.organizations (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS rbac.resource_actions
    ADD FOREIGN KEY (resource_id)
    REFERENCES rbac.resource (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS rbac.resource_actions
    ADD FOREIGN KEY (actions_id)
    REFERENCES rbac.actions (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS rbac.resource_actions_roles
    ADD FOREIGN KEY (resource_actions_id)
    REFERENCES rbac.resource_actions (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS rbac.resource_actions_roles
    ADD FOREIGN KEY (roles_id)
    REFERENCES rbac.roles (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS rbac.user_organization_roles
    ADD FOREIGN KEY (user_id)
    REFERENCES userdata.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS rbac.user_organization_roles
    ADD FOREIGN KEY (roles_id)
    REFERENCES rbac.roles (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS rbac.user_team_roles
    ADD FOREIGN KEY (team_id)
    REFERENCES userdata.teams (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS rbac.user_team_roles
    ADD FOREIGN KEY (roles_id)
    REFERENCES rbac.roles (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS rbac.user_team_roles
    ADD FOREIGN KEY (user_id)
    REFERENCES userdata.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;