version: '3'
services:
  postgres:
    networks:
      - common
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - 'db:/var/lib/postgresql/data'
      - type: bind
        source: ./init-db.sh
        target: /docker-entrypoint-initdb.d/init-db.sh
      - type: bind
        source: ./../scripts/init.sql
        target: /docker-entrypoint-initdb.d/init.sql
    ports:
      - '5432:5432'
    healthcheck:
      test:
        - CMD-SHELL
        - pg_isready
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  db:
    driver: local
networks:
  common:
    driver: bridge
