version: '3'
services:
  postgres:
    networks:
      - common
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - 'db:/var/lib/postgresql/data'
      - type: bind
        source: ./init-db.sh
        target: /docker-entrypoint-initdb.d/init-db.sh
      - type: bind
        source: ./../scripts/init.sql
        target: /docker-entrypoint-initdb.d/init.sql
    ports:
      - '5432:5432'
    healthcheck:
      test:
        - CMD-SHELL
        - pg_isready
      interval: 60s
      timeout: 5s
      retries: 5
  redis:
    image: bitnami/redis
    environment:
      - REDIS_PASSWORD=password123
    ports:
      - '6779:6379'
    healthcheck:
      test:
        - CMD-SHELL
        - redis-cli
        - ping
      interval: 60s
      timeout: 5s
      retries: 5
  pulsar:
    image: apachepulsar/pulsar
    ports:
      - '6650:6650'
      - '8080:8080'
    environment:
      PULSAR_MEM: " -Xms512m -Xmx512m -XX:MaxDirectMemorySize=1g"    
    healthcheck:
      test:
        - CMD-SHELL
        - pulsar-admin
        - broker-stats
        - monitoring-metrics
      interval: 60s
      timeout: 5s
      retries: 5
    volumes:
      - 'pulsardata:/pulsar/data'
      - 'pulsarconf:/pulsar/conf'
    command: bin/pulsar standalone

volumes:
  db:
    driver: local
  pulsardata:
    driver: local
  pulsarconf:
    driver: local
networks:
  common:
    driver: bridge
